# This is a TOML document. Boom
[discovery]
    nodes = ["127.0.0.1:7171"]

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["127.0.0.1:9092"]

[nsq]
    topic = "goim-push-topic"
    channel = "class100im"
    LookupAddr = "192.168.150.5:4161"